### ISSUE TITLE
Blank screen after login with Valora

### ISSUE THREAD

**Issue by hide-on-bush-x** [masa-finance/masa-react#148]
Steps to reproduce:

- Connect metamask and logout
- Try to connect wallet again and press switch account and use Valora to connect

I get empty white modal window that I can’t pass even if I signed transaction

Video: https://www.loom.com/share/f011a578e08148158fb7816d53106043

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.
